// Generated by scripts/build-client.mjs; edit client/index.mjs instead.
window.__ModuleLoader__.load({
  id: 'dsh-image-edge-cap',
  factory: (function createClientPlugin(require) {
  const React = require('react');
  const { createElement: h, useCallback, useEffect, useId, useRef, useState, useSyncExternalStore } = React;
  const SECTION_ID = 'dsh-image-edge-cap';
  const ENTRY_ID = 'dsh-image-edge-cap';
  const DEFAULT_EDGE = 2000;
  const MIN_EDGE = 16;
  const MAX_EDGE = 16384;
  const inject = ['slots', 'remote', 'remote.llm', 'remote.session'];
  const SAVE_ERROR = 'Could not save this setting. It may have changed elsewhere. Review the current value and try again.';
  const MODE_LABELS = { off: 'Off', all: 'All models', selected: 'Selected models' };

  function isRecord(value) {
    return value !== null && typeof value === 'object' && !Array.isArray(value);
  }

  function text(value, fallback) {
    return typeof value === 'string' && value.trim() !== '' ? value : fallback;
  }

  /** Settings namespace of this plugin's host entry among the served ones. */
  function findEntryNamespace(namespaces) {
    const ids = (Array.isArray(namespaces) ? namespaces : []).map(view => view?.ns).filter(id => typeof id === 'string');
    return ids.find(id => id === `include:${ENTRY_ID}`)
      ?? ids.find(id => id === ENTRY_ID)
      ?? ids.find(id => id.endsWith(`:${ENTRY_ID}`));
  }

  /** A stored rule in canonical form; anything malformed reads as off. */
  function normalizeRule(rule) {
    if (!isRecord(rule)) return { mode: 'off', models: [], maxImageEdge: DEFAULT_EDGE };
    const mode = rule.mode === 'all' || rule.mode === 'selected' ? rule.mode : 'off';
    const models = Array.isArray(rule.models) ? [...new Set(rule.models.filter(id => typeof id === 'string' && id !== ''))] : [];
    const edge = Number.isInteger(rule.maxImageEdge) && rule.maxImageEdge >= MIN_EDGE && rule.maxImageEdge <= MAX_EDGE
      ? rule.maxImageEdge : DEFAULT_EDGE;
    return { mode, models, maxImageEdge: edge };
  }

  /** Whether a rule caps anything (an empty selection caps nothing). */
  function ruleActive(rule) {
    const r = normalizeRule(rule);
    return r.mode === 'all' || (r.mode === 'selected' && r.models.length > 0);
  }

  /**
   * Join the registered providers, the model catalog, and the stored rules
   * into display rows. Pure, so tests can call it directly.
   * @param registered - `remote.llm.listProviders()` value.
   * @param groups - `remote.session.modelCatalog()` groups (`{ id, name, models }`).
   * @param rules - stored `providers` value.
   */
  function buildRows({ registered = [], groups = [], rules = {} }) {
    const catalog = new Map();
    for (const group of Array.isArray(groups) ? groups : []) {
      if (!isRecord(group) || typeof group.id !== 'string' || !Array.isArray(group.models)) continue;
      catalog.set(group.id, group.models
        .filter(model => isRecord(model) && typeof model.id === 'string' && model.id !== '')
        .map(model => ({ id: model.id, name: text(model.name, model.id) })));
    }
    const rows = new Map();
    for (const provider of Array.isArray(registered) ? registered : []) {
      if (!isRecord(provider) || typeof provider.id !== 'string' || provider.id === '') continue;
      rows.set(provider.id, { route: provider.id, name: text(provider.name, provider.id), active: true });
    }
    // A configured provider that no longer exists stays visible so its rule can be removed.
    for (const [route, rule] of Object.entries(isRecord(rules) ? rules : {})) {
      if (rows.has(route) || !ruleActive(rule)) continue;
      rows.set(route, { route, name: route, active: false });
    }
    return [...rows.values()]
      .map(row => {
        const known = catalog.get(row.route) ?? [];
        const rule = normalizeRule(rules?.[row.route]);
        const ids = new Set(known.map(model => model.id));
        // Selected models the catalog no longer lists stay visible so they can be cleared.
        const stale = rule.models.filter(id => !ids.has(id)).map(id => ({ id, name: id, stale: true }));
        return { ...row, models: [...known, ...stale] };
      })
      .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
  }

  /** Validate a draft and turn it into the settings op for one provider. */
  function draftToOp(route, draft) {
    const mode = draft.mode === 'all' || draft.mode === 'selected' ? draft.mode : 'off';
    if (mode === 'off') return { ok: true, op: { op: 'unset', path: ['providers', route] }, expected: undefined };
    const raw = String(draft.edge ?? '').trim();
    const edge = raw === '' ? DEFAULT_EDGE : Number(raw);
    if (!Number.isInteger(edge) || edge < MIN_EDGE || edge > MAX_EDGE) {
      return { ok: false, error: `Enter a whole number of pixels from ${MIN_EDGE} to ${MAX_EDGE}.` };
    }
    const models = mode === 'selected' ? [...new Set(draft.models)].sort() : [];
    if (mode === 'selected' && models.length === 0) {
      return { ok: false, error: 'Select at least one model, or choose “All models” or “Off”.' };
    }
    const value = { mode, models, maxImageEdge: edge };
    return { ok: true, op: { op: 'set', path: ['providers', route], value }, expected: value };
  }

  function sameRule(stored, expected) {
    if (expected === undefined) return !ruleActive(stored);
    const a = normalizeRule(stored);
    return a.mode === expected.mode && a.maxImageEdge === expected.maxImageEdge
      && a.models.length === expected.models.length && [...a.models].sort().every((id, i) => id === expected.models[i]);
  }

  const styles = {
    page: { display: 'flex', flexDirection: 'column', gap: '16px', maxWidth: '760px', fontSize: '13px', color: 'var(--dsw-alias-label-primary)' },
    title: { margin: 0, fontSize: '18px', lineHeight: '26px', fontWeight: 600 },
    lead: { margin: '4px 0 0', lineHeight: '20px', color: 'var(--dsw-alias-label-secondary)' },
    notice: {
      margin: 0, padding: '10px 12px', border: '1px solid var(--dsw-alias-border-l1)',
      borderInlineStart: '3px solid var(--dsw-alias-state-warn-primary)', borderRadius: '8px',
      fontSize: '12px', lineHeight: '18px', color: 'var(--dsw-alias-label-secondary)', overflowWrap: 'anywhere',
    },
    list: { listStyle: 'none', margin: 0, padding: 0, border: '1px solid var(--dsw-alias-border-l1)', borderRadius: '8px', overflow: 'hidden' },
    row: { display: 'flex', flexDirection: 'column', gap: '8px', padding: '10px 12px', borderTop: '1px solid var(--dsw-alias-border-l1)', minWidth: 0 },
    rowFirst: { borderTop: 'none' },
    rowHead: { display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap', minWidth: 0 },
    rowText: { display: 'flex', flexDirection: 'column', gap: '2px', minWidth: 0, flex: 1 },
    rowName: { fontWeight: 500, overflowWrap: 'anywhere' },
    rowMeta: { fontSize: '12px', color: 'var(--dsw-alias-label-secondary)', overflowWrap: 'anywhere' },
    controls: { display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0, flexWrap: 'wrap' },
    field: {
      padding: '4px 8px', boxSizing: 'border-box', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '6px',
      background: 'transparent', color: 'inherit', font: 'inherit',
    },
    edge: { width: '96px' },
    unit: { fontSize: '12px', color: 'var(--dsw-alias-label-secondary)' },
    models: {
      display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '4px 12px',
      margin: 0, padding: '8px 10px', border: '1px solid var(--dsw-alias-border-l1)', borderRadius: '6px', minWidth: 0,
    },
    legend: { padding: '0 4px', fontSize: '12px', color: 'var(--dsw-alias-label-secondary)' },
    check: { display: 'flex', alignItems: 'center', gap: '6px', minWidth: 0, overflowWrap: 'anywhere', cursor: 'pointer' },
    button: {
      alignSelf: 'flex-start', padding: '4px 12px', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '6px',
      background: 'transparent', color: 'inherit', font: 'inherit', cursor: 'pointer',
    },
    buttonDisabled: { opacity: 0.45, cursor: 'default' },
    status: { margin: 0, color: 'var(--dsw-alias-label-secondary)' },
    error: { margin: 0, color: 'var(--dsw-alias-state-error-primary)' },
  };

  const emptyMirror = { view: undefined };
  const unavailableSnapshot = { status: 'unavailable', value: undefined, revision: undefined, writable: false, mode: 'host' };
  const noForm = { getSnapshot: () => unavailableSnapshot, subscribe: () => () => {}, mutate: async () => false };

  function useStore(store, fallback) {
    const subscribe = useCallback(listener => (store ? store.subscribe(listener) : () => {}), [store]);
    const getSnapshot = useCallback(() => (store ? store.getSnapshot() : fallback), [store, fallback]);
    return useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
  }

  function summary(row, rule) {
    const r = normalizeRule(rule);
    const where = row.active ? row.route : `${row.route} · no longer configured. Set it to Off to remove the rule.`;
    if (r.mode === 'all') return `${where} · all models capped at ${r.maxImageEdge} px`;
    if (r.mode === 'selected' && r.models.length > 0) {
      return `${where} · ${r.models.length} model${r.models.length === 1 ? '' : 's'} capped at ${r.maxImageEdge} px`;
    }
    return `${where} · not capped`;
  }

  function draftFrom(rule) {
    const r = normalizeRule(rule);
    return { mode: ruleActive(r) ? r.mode : 'off', edge: String(r.maxImageEdge), models: r.models };
  }

  function ProviderRow({ row, first, saved, revision, disabled, catalogStatus, onSave }) {
    const modeId = useId();
    const edgeId = useId();
    const detailId = useId();
    const [draft, setDraft] = useState(() => draftFrom(saved));
    const [dirty, setDirty] = useState(false);
    // Follow every committed change (this save, another tab, a reload).
    useEffect(() => {
      setDraft(draftFrom(saved));
      setDirty(false);
    }, [saved, revision, row.route]);
    const current = dirty ? draft : draftFrom(saved);
    const edit = patch => { setDraft({ ...current, ...patch }); setDirty(true); };
    const toggle = id => {
      const set = new Set(current.models);
      if (set.has(id)) set.delete(id); else set.add(id);
      edit({ models: [...set] });
    };

    let picker = null;
    if (current.mode === 'selected') {
      if (row.models.length === 0) {
        picker = h('p', { style: styles.status },
          catalogStatus === 'loading' ? 'Loading models…'
            : catalogStatus === 'error' ? 'Could not load this provider’s models.'
              : 'This provider lists no models.');
      } else {
        picker = h('fieldset', { style: styles.models },
          h('legend', { style: styles.legend }, `Models to cap (${current.models.length} selected)`),
          row.models.map(model => h('label', { key: model.id, style: styles.check, title: model.id },
            h('input', {
              type: 'checkbox', disabled,
              checked: current.models.includes(model.id),
              onChange: () => toggle(model.id),
            }),
            h('span', null, model.stale ? `${model.id} (no longer listed)` : model.name))));
      }
    }

    return h('li', { style: first ? { ...styles.row, ...styles.rowFirst } : styles.row },
      h('div', { style: styles.rowHead },
        h('span', { style: styles.rowText },
          h('label', { htmlFor: modeId, style: styles.rowName }, row.name),
          h('span', { id: detailId, style: styles.rowMeta }, summary(row, saved))),
        h('span', { style: styles.controls },
          h('select', {
            id: modeId, value: current.mode, disabled, style: styles.field,
            'aria-label': `Image cap mode for ${row.route}`, 'aria-describedby': detailId,
            onChange: event => edit({ mode: event.currentTarget.value }),
          }, Object.entries(MODE_LABELS).map(([value, label]) => h('option', { key: value, value }, label))),
          current.mode === 'off' ? null : h('label', { htmlFor: edgeId, style: styles.unit }, 'Max edge'),
          current.mode === 'off' ? null : h('input', {
            id: edgeId, type: 'number', min: MIN_EDGE, max: MAX_EDGE, step: 1, placeholder: String(DEFAULT_EDGE),
            value: current.edge, disabled, style: { ...styles.field, ...styles.edge },
            'aria-label': `Longest image side in pixels for ${row.route}`,
            onChange: event => edit({ edge: event.currentTarget.value }),
          }),
          current.mode === 'off' ? null : h('span', { style: styles.unit }, 'px'),
          h('button', {
            type: 'button', disabled: disabled || !dirty,
            style: disabled || !dirty ? { ...styles.button, ...styles.buttonDisabled } : styles.button,
            onClick: () => onSave(row.route, current),
          }, 'Apply'))),
      picker);
  }

  function ImageSizeSection({ source }) {
    const mirrorSnapshot = useStore(source.describe, emptyMirror);
    const namespaces = mirrorSnapshot?.view?.namespaces ?? [];
    const form = source.formFor(namespaces);
    const snapshot = useStore(form ?? noForm, unavailableSnapshot);
    const [directory, setDirectory] = useState({ status: 'loading', registered: [], error: '' });
    const [catalog, setCatalog] = useState({ status: 'loading', groups: [] });
    const [pending, setPending] = useState('');
    const [error, setError] = useState('');
    const busy = useRef(false);
    const mounted = useRef(true);
    const generation = useRef(0);

    const load = useCallback(async () => {
      const current = ++generation.current;
      const settle = fn => { if (mounted.current && current === generation.current) fn(); };
      const providers = (async () => {
        try {
          const registered = await source.listProviders();
          if (!registered?.ok) throw new Error('list failed');
          settle(() => setDirectory({ status: 'ready', registered: Array.isArray(registered.value) ? registered.value : [], error: '' }));
        } catch {
          settle(() => setDirectory(previous => ({ ...previous, status: 'error', error: 'Could not load the provider list.' })));
        }
      })();
      const models = (async () => {
        try {
          const response = await source.modelCatalog();
          if (!response?.ok) throw new Error('catalog failed');
          settle(() => setCatalog({ status: 'ready', groups: Array.isArray(response.value?.groups) ? response.value.groups : [] }));
        } catch {
          settle(() => setCatalog(previous => ({ ...previous, status: 'error' })));
        }
      })();
      await Promise.all([providers, models]);
    }, [source]);

    useEffect(() => {
      mounted.current = true;
      try { void source.describe?.ensure?.(); } catch { /* the mirror reports its own failure */ }
      void load();
      const off = source.onInvalidate(() => { void load(); });
      return () => { mounted.current = false; off(); };
    }, [source, load]);

    const rules = isRecord(snapshot.value?.providers) ? snapshot.value.providers : {};
    const rows = buildRows({ registered: directory.registered, groups: catalog.groups, rules });
    const writable = snapshot.status === 'ready' && snapshot.writable === true && snapshot.mode === 'host';

    async function save(route, draft) {
      if (!writable || busy.current || form === undefined) return;
      const planned = draftToOp(route, draft);
      if (!planned.ok) {
        if (mounted.current) setError(planned.error);
        return;
      }
      busy.current = true;
      setPending(route);
      setError('');
      try {
        // Fence the rendered revision, then confirm the stored value: a
        // refused write can settle without throwing.
        await form.mutate([planned.op], snapshot.revision);
        const settled = form.getSnapshot();
        if (settled.status !== 'ready' || !sameRule(settled.value?.providers?.[route], planned.expected)) {
          throw new Error('Setting was not confirmed');
        }
      } catch {
        // Never render raw transport errors: they can carry configuration details.
        if (mounted.current) setError(SAVE_ERROR);
      } finally {
        busy.current = false;
        if (mounted.current) setPending('');
      }
    }

    let status = null;
    if (mirrorSnapshot?.view === undefined && form === undefined) status = 'Loading settings…';
    else if (form === undefined || snapshot.status === 'unavailable') {
      status = 'The dsh-image-edge-cap host plugin is not running, so these settings cannot be changed. Check the dsh startup output: the plugin refuses to load on an unsupported DSH version.';
    } else if (snapshot.status === 'loading') status = 'Loading settings…';
    else if (!writable) status = 'These settings are read-only in this browser.';

    const cappedCount = rows.filter(row => ruleActive(rules[row.route])).length;
    return h('section', { style: styles.page, 'aria-labelledby': `${SECTION_ID}-title` },
      h('header', null,
        h('h2', { id: `${SECTION_ID}-title`, style: styles.title }, 'Image size'),
        h('p', { style: styles.lead },
          'Shrinks every image sent to the chosen models so its longest side is at most the given number of pixels, keeping the aspect ratio. ',
          'Use it for routes that reach Anthropic, which rejects requests with more than 20 images when any image is over 2000 px on a side.')),
      h('p', { role: 'note', style: styles.notice },
        'Only the copy sent to the model is resized. Stored attachments and session history are never changed. ',
        'Rules apply to the next request, including resumed sessions and subagents. Every provider is off by default.'),
      status === null ? null : h('p', { role: 'status', style: styles.status }, status),
      directory.status === 'loading' && rows.length === 0 ? h('p', { role: 'status', style: styles.status }, 'Loading providers…') : null,
      directory.status === 'error' || catalog.status === 'error'
        ? h('div', { style: { display: 'flex', flexDirection: 'column', gap: '8px' } },
          h('p', { role: 'alert', style: styles.error },
            directory.status === 'error' ? directory.error : 'Could not load the model list. Choosing specific models is unavailable until it loads.'),
          h('button', { type: 'button', style: styles.button, onClick: () => { void load(); } }, 'Retry'))
        : null,
      directory.status === 'ready' && rows.length === 0
        ? h('p', { style: styles.status }, 'No model providers are configured yet. Add one in Settings → Models.')
        : null,
      rows.length > 0
        ? h('div', { style: { display: 'flex', flexDirection: 'column', gap: '6px' } },
          h('p', { style: styles.status }, `Providers (${cappedCount} capped)`),
          h('ul', { style: styles.list, 'aria-label': 'Providers' },
            rows.map((row, index) => h(ProviderRow, {
              key: row.route, row, first: index === 0,
              saved: rules[row.route],
              revision: snapshot.revision,
              disabled: !writable || pending !== '',
              catalogStatus: catalog.status,
              onSave: (route, draft) => { void save(route, draft); },
            }))))
        : null,
      pending !== '' ? h('p', { role: 'status', style: styles.status }, 'Saving…') : null,
      error !== '' ? h('p', { role: 'alert', style: styles.error }, error) : null);
  }

  function apply(ctx) {
    const remote = {
      listProviders: () => ctx.remote.llm.listProviders(),
      modelCatalog: () => ctx.remote.session.modelCatalog(),
      onInvalidate(listener) {
        if (typeof ctx.remote.$on !== 'function') return () => {};
        const offs = ['llm/adapters-updated', 'settings/document-updated'].map(event => {
          try { return ctx.remote.$on(event, listener); } catch { return undefined; }
        }).filter(off => typeof off === 'function');
        return () => { for (const off of offs) off(); };
      },
    };
    ctx.inject(['configForms'], child => {
      const forms = child.configForms;
      let cached;
      const source = {
        ...remote,
        describe: forms.describe(),
        formFor(namespaces) {
          const ns = findEntryNamespace(namespaces);
          if (ns === undefined) return undefined;
          if (cached?.ns !== ns) cached = { ns, form: forms.get(ns) };
          return cached.form;
        },
      };
      child.slots.inject('settings.section', () => child.slots.register({
        name: 'settings.section',
        id: SECTION_ID,
        order: 62,
        label: () => 'Image size',
        inject: () => ({ source }),
      }, ImageSizeSection));
    });
  }

  return { inject, apply, buildRows, findEntryNamespace, normalizeRule, draftToOp, sameRule };
})
});
